services:
  xdcc-extractor:
    build: .
    container_name: xdcc-extractor
    restart: unless-stopped

    ports:
      - "8099:8099"

    environment:
      TZ: Europe/Berlin

    volumes:
      - /media/HDD3/XDCC:/downloads
      - ./config.docker.toml:/app/config.toml:rw
      - ./state:/state
      - ./config:/config:rw
